import mongoose, { Schema, Document } from 'mongoose';

/**
 * Execution file (generated by code - images, text files, etc.)
 */
export interface IExecutionFile {
  name: string;
  type: 'image' | 'text' | 'data';
  data: string; // base64 for binary, plain text for text
  mimeType: string;
}

/**
 * Execution result document interface
 */
export interface IExecutionResult extends Document {
  jobId: string;
  userId: string;
  problemId?: number;
  code: string;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  result?: {
    stdout: string;
    stderr: string;
    status: 'Success' | 'Error' | 'Timeout';
    executionTime: number;
    exitCode?: number;
    // Generated files (images, CSVs, etc.)
    files?: IExecutionFile[];
    // Legacy fields
    plots?: string[];
  };
  submissionResult?: {
    status: 'Accepted' | 'Wrong Answer' | 'Time Limit Exceeded' | 'Error';
    passed: number;
    failed: number;
    total: number;
    passRate: number;
    allPassed: boolean;
    executionTime: number;
    testResults?: Array<{
      input: string;
      expected_output: string;
      actual_output: string;
      status: 'passed' | 'failed';
      error?: string;
      is_hidden?: boolean;
    }>;
  };
  error?: string;
  createdAt: Date;
  completedAt?: Date;
}

const ExecutionResultSchema = new Schema<IExecutionResult>({
  jobId: {
    type: String,
    required: true,
    unique: true,
  },
  userId: {
    type: String,
    required: true,
  },
  problemId: Number,
  code: {
    type: String,
    required: true,
  },
  status: {
    type: String,
    enum: ['pending', 'processing', 'completed', 'failed'],
    default: 'pending',
  },
  result: Schema.Types.Mixed,
  submissionResult: Schema.Types.Mixed,
  error: String,
  createdAt: {
    type: Date,
    default: Date.now,
    expires: 604800, // Auto-delete after 7 days (604800 seconds)
  },
  completedAt: Date,
}, {
  collection: 'execution_results',
});

// Indexes
// Note: jobId unique index and createdAt TTL index are automatically created by schema field definitions
ExecutionResultSchema.index({ userId: 1, createdAt: -1 });
ExecutionResultSchema.index({ status: 1, createdAt: -1 });

export const ExecutionResult = mongoose.models.ExecutionResult || mongoose.model<IExecutionResult>('ExecutionResult', ExecutionResultSchema);
